### ISSUE TITLE
Serial debug on low speed cause errors with read. 

### ISSUE THREAD

**Issue by Tolmeros** [Harvie/ps2dev#2]
Debug in library enabled and serial baud is `9600`.
Keyboard received `0xED: //set/reset LEDs ` command.
Method `read()` infinitely return `-1` when it tried to receive command's argument.

When debug disabled keyboard able to receive leds changes.
Also I tried set serial baud rate to `115200` and enable debug. And it works fine.

**Comment by Harvie** [comment]
I've used serial debug only for few moments. It's absolutely not supposed to be left enabled all the time. I should mention this in README. Do you have any other suggestions on this one?

**Comment by Tolmeros** [comment]
The debug might important for DIY devices. But I think it will be enough a mention in README how to setup debugging correctly.

**Comment by Harvie** [comment]
I've been mostly using it to debug the library when it was broken (i've even ran into some weird compiler bug). Library users should not need it at all as long as the library works.
