### ISSUE TITLE
STM8S port?

### ISSUE THREAD

**Issue by tinkerBOY-git** [Harvie/ps2dev#9]
Is there any available port of this library to STM8S mcu?

**Comment by Harvie** [comment]
Hello. Currently Arduino API is supported. I've done quick googling and it seems to be possible to program STM8S using Arduino libraries, which means it might be possible. But i didn't tested it.

If there is some issue, we can tweak the code to work better.

Also if you don't want to use Arduino libraries, we probably can add header file with HAL layer, which will use #ifdefs and #defines to automaticaly translate calls to any platform that you are building on. I will accept such PR if the code will be somewhat meaningful.

**Comment by Harvie** [comment]
I am closing this now, please let me know if there are some specific changes that need to be done to the code in order to fit your case.
